/**
 * Seed list of 120 substance names for bulk import.
 * Names are canonical English/German as commonly referenced in pharmacological literature.
 */
export const SUBSTANCE_SEED_LIST: string[] = [
  "Psilocybin",
  "LSD",
  "DMT",
  "Mescalin",
  "MDMA",
  "Ketamin",
  "THC",
  "CBD",
  "Kokain",
  "Amphetamin",
  "Methamphetamin",
  "Heroin",
  "Morphin",
  "Codein",
  "Fentanyl",
  "Oxycodon",
  "Tramadol",
  "Methadon",
  "Buprenorphin",
  "Diazepam",
  "Alprazolam",
  "Lorazepam",
  "Clonazepam",
  "Midazolam",
  "Zolpidem",
  "GHB",
  "GBL",
  "Phenibut",
  "Gabapentin",
  "Pregabalin",
  "Nikotin",
  "Koffein",
  "Alkohol (Ethanol)",
  "Lachgas (N2O)",
  "Salvinorin A",
  "Ibogain",
  "Ayahuasca",
  "5-MeO-DMT",
  "2C-B",
  "2C-E",
  "2C-I",
  "DOB",
  "DOM",
  "MDA",
  "4-FA",
  "Methylon",
  "Mephedron",
  "MDPV",
  "Alpha-PVP",
  "Cathinon",
  "Kratom (Mitragynin)",
  "Modafinil",
  "Methylphenidat",
  "Atomoxetin",
  "Bupropion",
  "Dextromethorphan (DXM)",
  "Diphenhydramin",
  "Promethazin",
  "Scopolamin",
  "Atropin",
  "PCP",
  "3-MeO-PCP",
  "MXE (Methoxetamin)",
  "DXE (Deschloroketamin)",
  "Ephedrin",
  "Pseudoephedrin",
  "Phenylethylamin (PEA)",
  "Tryptamin",
  "AMT (Alpha-Methyltryptamin)",
  "DiPT",
  "4-AcO-DMT",
  "4-HO-MET",
  "4-HO-MiPT",
  "ETH-LAD",
  "AL-LAD",
  "1P-LSD",
  "ALD-52",
  "LSA",
  "Muscimol",
  "Ibotensäure",
  "Clomethiazol",
  "Baclofen",
  "Carisoprodol",
  "Meprobamat",
  "Barbital",
  "Phenobarbital",
  "Thiopental",
  "Propofol",
  "Dexmedetomidin",
  "Clonidin",
  "Tianeptin",
  "Fluoxetin",
  "Sertralin",
  "Citalopram",
  "Venlafaxin",
  "Duloxetin",
  "Mirtazapin",
  "Quetiapin",
  "Olanzapin",
  "Risperidon",
  "Aripiprazol",
  "Haloperidol",
  "Chlorpromazin",
  "Lithium",
  "Valproat",
  "Carbamazepin",
  "Lamotrigin",
  "Topiramat",
  "Amantadin",
  "Memantin",
  "Naloxon",
  "Naltrexon",
  "Disulfiram",
  "Acamprosat",
  "Vareniclin",
  "Cytisin",
  "Piracetam",
  "Aniracetam",
  "Oxiracetam",
  "Noopept",
  "L-Theanin",
  "Ashwagandha",
  "Rhodiola Rosea",
  "Johanniskraut",
];
